#!/bin/bash
# export JAVA_HOME="" # Set here if not set in environment
# export CUDA_PATH="" # Set here if not set in environment
# export SPARK_HOME="" # Set here if not set in environment
BIDMACH_ROOT="${BASH_SOURCE[0]}"
if [ ! `uname` = "Darwin" ]; then
  BIDMACH_ROOT=`readlink -f "${BIDMACH_ROOT}"`
else
  while [ -L "${BIDMACH_ROOT}" ]; do
    BIDMACH_ROOT=`readlink "${BIDMACH_ROOT}"`
  done
fi
BIDMACH_ROOT=`dirname "$BIDMACH_ROOT"`
pushd "${BIDMACH_ROOT}"  > /dev/null
BIDMACH_ROOT=`pwd`
BIDMACH_ROOT="$( echo ${BIDMACH_ROOT} | sed s+/cygdrive/c+c:+ )"

BIDMACH_JAR=`echo target/BIDMachSpark-*-assembly.jar`

OPTS=$(getopt -o m:j: --long master:,jars: -n 'parse-options' -- "$@")
[[ $? -ne 0 ]] && echo 'Failed parsing options.' >&2 && exit 1
eval set -- "$OPTS"

MASTER="spark://${HOSTNAME}:7077"
JARS="${BIDMACH_JAR}"
OTHER=

while true; do
  case "$1" in
    -m | --master ) MASTER="$2"; shift; shift;;
    -j | --jars ) JARS="$2"; shift; shift;;
    -- ) shift; break;;
    * ) break;;
  esac
done

${SPARK_HOME}/bin/spark-shell --master $MASTER --jars $JARS $@
